package com.lyrebirdstudio.pointlist;

import android.graphics.PointF;

import com.google.android.exoplayer2.trackselection.AdaptiveVideoTrackSelection;

import java.util.ArrayList;
import java.util.List;

public class Collage3 extends Collage {
    public static int shapeCount = 3;

    public Collage3(int width, int height) {
        this.collageLayoutList = new ArrayList();
        PointF[]  points = new PointF[4];
        ArrayList arrayList = new ArrayList();
        List<PointF[]> shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        CollageLayout collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 0));
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.41601562f * ((float) height)), new PointF(1.0f * ((float) width), 0.41601562f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.768f * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.768f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6f * ((float) height)), new PointF(1.0f * ((float) width), 0.6f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 105));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 106));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 107));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6972656f * ((float) width), 0.0f * ((float) height)), new PointF(0.6972656f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF((1.0f - 0.68654686f) * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF((1.0f - 0.68654686f) * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.142f * ((float) width), 0.182f * ((float) height)), new PointF(0.84f * ((float) width), 0.182f * ((float) height)), new PointF(0.84f * ((float) width), 0.805f * ((float) height)), new PointF(0.142f * ((float) width), 0.805f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 75));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 77));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 76));
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        points = new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))};
        shapeList.add(points);
        shapeList.add(points);
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 99));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 100));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 101));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.65f * ((float) height)), new PointF(1.0f * ((float) width), 0.65f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 102));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 103));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 104));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 9));
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.58f * ((float) width), 0.5f * ((float) height)), new PointF(0.58f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.58f * ((float) width), 1.0f * ((float) height)), new PointF(0.58f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.42f * ((float) width), 0.25f * ((float) height)), new PointF(0.42f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 9));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.46f * ((float) width), 0.0f * ((float) height)), new PointF(0.46f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.46f * ((float) width), 1.0f * ((float) height)), new PointF(0.46f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.54f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.54f * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 0));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.02f * ((float) width), 0.02f * ((float) height)), new PointF(0.02f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.02f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.52f * ((float) width), 0.02f * ((float) height)), new PointF(1.0f * ((float) width), 0.02f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.52f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.48f * ((float) height)), new PointF(1.0f * ((float) width), 0.48f * ((float) height)), new PointF(1.0f * ((float) width), 0.98f * ((float) height)), new PointF(0.0f * ((float) width), 0.98f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.25f * ((float) height)), new PointF(0.2f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.8f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.8f * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.25f * ((float) height)), new PointF(0.2f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.8f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.8f * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.setClearIndex(2);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.5833333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5833333f * ((float) width), 0.5833333f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.0f * ((float) width), 0.41666666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 1.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.8333333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.8333333f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.8333333f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.8333333f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
    }
}
