package com.lyrebirdstudio.pointlist;

import android.graphics.PointF;

import java.util.ArrayList;
import java.util.List;

public class Collage1 extends Collage {
    public static int shapeCount = 1;

    public Collage1(int width, int height) {
        this.collageLayoutList = new ArrayList();
        List<PointF[]> shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        CollageLayout collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 3));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 7));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 2));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 4));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 6));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 10));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 9));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 8));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 1));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 5));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 11));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 12));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 13));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 14));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 15));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 16));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 17));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 18));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 19));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 20));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 21));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 22));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 23));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 24));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 25));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 26));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 27));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 28));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 29));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 30));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 31));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 32));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 33));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 34));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 35));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 36));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 37));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 38));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 39));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 40));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 41));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 42));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 43));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 44));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 45));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 46));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 47));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 48));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 49));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 50));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 51));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 52));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 53));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 54));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 55));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 56));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 57));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 58));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 59));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 60));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 61));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 62));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 63));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 64));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 65));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 66));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 67));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 68));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(((float) width) * 0.0f, ((float) height) * 0.0f), new PointF(((float) width) * 0.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 1.0f), new PointF(((float) width) * 1.0f, ((float) height) * 0.0f)});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 69));
        this.collageLayoutList.add(collageLayout);
    }
}
