package com.lyrebirdstudio.pointlist;

import android.graphics.PointF;

import com.google.android.exoplayer2.trackselection.AdaptiveVideoTrackSelection;

import java.util.ArrayList;
import java.util.List;

public class Collage5 extends Collage {
    public static int shapeCount = 5;

    public Collage5(int width, int height) {
        this.collageLayoutList = new ArrayList();
        PointF[]  points = new PointF[4];
        List<PointF[]> shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.7083333f * ((float) height)), new PointF(0.7083333f * ((float) width), 0.7083333f * ((float) height)), new PointF(0.7083333f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.29166666f * ((float) width), 0.0f * ((float) height)), new PointF(0.29166666f * ((float) width), 0.7083333f * ((float) height)), new PointF(0.0f * ((float) width), 0.7083333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.29166666f * ((float) height)), new PointF(0.29166666f * ((float) width), 0.29166666f * ((float) height)), new PointF(0.29166666f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.7083333f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.29166666f * ((float) height)), new PointF(0.7083333f * ((float) width), 0.29166666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.29166666f * ((float) width), 0.7083333f * ((float) height)), new PointF(0.29166666f * ((float) width), 0.29166666f * ((float) height)), new PointF(0.7083333f * ((float) width), 0.29166666f * ((float) height)), new PointF(0.7083333f * ((float) width), 0.7083333f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.2f * ((float) height)), new PointF(0.38889167f * ((float) width), 0.38889167f * ((float) height)), new PointF(0.2f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.8f * ((float) width), 0.5f * ((float) height)), new PointF(0.61111087f * ((float) width), 0.38889167f * ((float) height)), new PointF(0.5f * ((float) width), 0.2f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.2f * ((float) width), 0.5f * ((float) height)), new PointF(0.38889167f * ((float) width), 0.6110833f * ((float) height)), new PointF(0.5f * ((float) width), 0.8f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.8f * ((float) height)), new PointF(0.61110836f * ((float) width), 0.61110836f * ((float) height)), new PointF(0.8f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.8f * ((float) height)), new PointF(0.38889167f * ((float) width), 0.6110833f * ((float) height)), new PointF(0.2f * ((float) width), 0.5f * ((float) height)), new PointF(0.38889167f * ((float) width), 0.38889167f * ((float) height)), new PointF(0.5f * ((float) width), 0.2f * ((float) height)), new PointF(0.61111087f * ((float) width), 0.38889167f * ((float) height)), new PointF(0.8f * ((float) width), 0.5f * ((float) height)), new PointF(0.61110836f * ((float) width), 0.61110836f * ((float) height))});
        CollageLayout collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.checkForConcavite = true;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(4, 0));
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5352f * ((float) height)), new PointF(0.5352f * ((float) width), 0.5352f * ((float) height)), new PointF(0.5352f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5352f * ((float) width), 1.0f * ((float) height)), new PointF(0.5352f * ((float) width), 0.4648f * ((float) height)), new PointF(0.0f * ((float) width), 0.4648f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.4648f * ((float) width), 0.5352f * ((float) height)), new PointF(1.0f * ((float) width), 0.5352f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.4648f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.4648f * ((float) width), 1.0f * ((float) height)), new PointF(0.4648f * ((float) width), 0.4648f * ((float) height)), new PointF(1.0f * ((float) width), 0.4648f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.181f * ((float) width), 0.181f * ((float) height)), new PointF(0.181f * ((float) width), 0.819f * ((float) height)), new PointF(0.819f * ((float) width), 0.819f * ((float) height)), new PointF(0.819f * ((float) width), 0.181f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 97));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 94));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 96));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 95));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(4, 98));
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.25f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.252f * ((float) height)), new PointF(0.252f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.748f * ((float) height)), new PointF(0.748f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 78));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 79));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 80));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 81));
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.25f * ((float) height)), new PointF(0.25f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(4, 1));
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.2f * ((float) width), 0.2f * ((float) height)), new PointF(0.2f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.8f * ((float) height)), new PointF(0.8f * ((float) width), 0.2f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(4, 0));
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.25f * ((float) height)), new PointF(0.25f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.25f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.setClearIndex(4);
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.checkForConcavite = true;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.checkForConcavite = true;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.25f * ((float) width), 1.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.25f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.0f * ((float) width), 0.41666666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 0.25f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 0.5f * ((float) height)), new PointF(0.5833333f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5833333f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 0.5f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.16666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(0.0f * ((float) width), 0.16666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.25f * ((float) height)), new PointF(0.33333334f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.25f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.16666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(1.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.25f * ((float) height)), new PointF(0.6666667f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.16666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(0.6666667f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
    }
}
