package com.lyrebirdstudio.pointlist;

import android.graphics.PointF;

import com.google.android.exoplayer2.trackselection.AdaptiveVideoTrackSelection;
import com.lyrebirdstudio.lyrebirdlibrary.BlurBuilderNormal;

import java.util.ArrayList;
import java.util.List;

public class Collage4 extends Collage {
    public static int shapeCount = 4;

    public Collage4(int width, int height) {
        this.collageLayoutList = new ArrayList();
        PointF[] points = new PointF[4];
        ArrayList arrayList = new ArrayList();
        List<PointF[]> shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.567f * ((float) height)), new PointF(0.579f * ((float) width), 0.567f * ((float) height)), new PointF(0.579f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.647f * ((float) width), 1.0f * ((float) height)), new PointF(0.647f * ((float) width), 0.493f * ((float) height)), new PointF(0.0f * ((float) width), 0.493f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.478f * ((float) width), 0.528f * ((float) height)), new PointF(1.0f * ((float) width), 0.528f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.478f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.443f * ((float) width), 1.0f * ((float) height)), new PointF(0.443f * ((float) width), 0.426f * ((float) height)), new PointF(1.0f * ((float) width), 0.426f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        CollageLayout collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 90));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 91));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 92));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 93));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 86));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 87));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 88));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 89));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.575f * ((float) height)), new PointF(0.575f * ((float) width), 0.575f * ((float) height)), new PointF(0.575f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.575f * ((float) width), 1.0f * ((float) height)), new PointF(0.575f * ((float) width), 0.425f * ((float) height)), new PointF(0.0f * ((float) width), 0.425f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.425f * ((float) width), 0.575f * ((float) height)), new PointF(1.0f * ((float) width), 0.575f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.425f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.425f * ((float) width), 1.0f * ((float) height)), new PointF(0.425f * ((float) width), 0.425f * ((float) height)), new PointF(1.0f * ((float) width), 0.425f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 74));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 72));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 73));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 71));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.26f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.26f * ((float) width), 0.6f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.74f * ((float) width), BlurBuilderNormal.BITMAP_SCALE * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.26f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.74f * ((float) width), BlurBuilderNormal.BITMAP_SCALE * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.6f * ((float) width), 0.74f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.26f * ((float) width), 0.6f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.6f * ((float) width), 0.74f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.checkForConcavite = true;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.625f * ((float) height)), new PointF(0.415f * ((float) width), 0.625f * ((float) height)), new PointF(0.415f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.585f * ((float) width), 0.0f * ((float) height)), new PointF(0.585f * ((float) width), 0.375f * ((float) height)), new PointF(1.0f * ((float) width), 0.375f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.575f * ((float) height)), new PointF(0.425f * ((float) width), 0.575f * ((float) height)), new PointF(0.575f * ((float) width), 0.425f * ((float) height)), new PointF(0.575f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.425f * ((float) height)), new PointF(0.575f * ((float) width), 0.425f * ((float) height)), new PointF(0.425f * ((float) width), 0.575f * ((float) height)), new PointF(0.425f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 1));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.35f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.35f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.65f * ((float) height)), new PointF(1.0f * ((float) width), 0.65f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.45f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.45f * ((float) height)), new PointF(0.6f * ((float) width), 0.6f * ((float) height)), new PointF(0.6f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.55f * ((float) height)), new PointF(0.6f * ((float) width), 0.55f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), BlurBuilderNormal.BITMAP_SCALE * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 0));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.675f * ((float) height)), new PointF(0.375f * ((float) width), 0.675f * ((float) height)), new PointF(0.375f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.325f * ((float) height)), new PointF(1.0f * ((float) width), 0.325f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.541f * ((float) height)), new PointF(0.375f * ((float) width), 0.541f * ((float) height)), new PointF(0.625f * ((float) width), 0.375f * ((float) height)), new PointF(0.625f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.459f * ((float) height)), new PointF(0.625f * ((float) width), 0.459f * ((float) height)), new PointF(0.375f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 9));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.35f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.35f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.65f * ((float) height)), new PointF(1.0f * ((float) width), 0.65f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.45f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.45f * ((float) height)), new PointF(0.6f * ((float) width), 0.6f * ((float) height)), new PointF(0.6f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.55f * ((float) height)), new PointF(0.6f * ((float) width), 0.55f * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), BlurBuilderNormal.BITMAP_SCALE * ((float) height)), new PointF(BlurBuilderNormal.BITMAP_SCALE * ((float) width), 0.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 1));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 0));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 0));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 1));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 1));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        collageLayout.maskPairListSvg.add(new MaskPairSvg(0, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(1, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(2, 9));
        collageLayout.maskPairListSvg.add(new MaskPairSvg(3, 9));
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.25f * ((float) width), 1.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.25f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.25f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 1.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) width), 0.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f, 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.3333333f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.3333333f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.3333333f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.3333333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.66667f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.51110834f * ((float) width), 0.53333336f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.51110834f * ((float) width), 0.53333336f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.4888892f * ((float) width), 0.46666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.4888892f * ((float) width), 0.46666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5555558f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.44444168f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5555558f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.44444168f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.375f * ((float) height)), new PointF(1.0f * ((float) width), 0.375f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 0.625f * ((float) height)), new PointF(0.625f * ((float) width), 0.375f * ((float) height)), new PointF(0.625f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.375f * ((float) height)), new PointF(0.625f * ((float) width), 0.375f * ((float) height)), new PointF(0.375f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.375f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.0f * ((float) height)), new PointF(0.375f * ((float) width), 0.375f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 1.0f * ((float) height)), new PointF(0.625f * ((float) width), 0.625f * ((float) height)), new PointF(1.0f * ((float) width), 0.625f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.375f * ((float) height)), new PointF(0.375f * ((float) width), 0.375f * ((float) height)), new PointF(0.625f * ((float) width), 0.625f * ((float) height)), new PointF(0.625f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.625f * ((float) height)), new PointF(0.625f * ((float) width), 0.625f * ((float) height)), new PointF(0.375f * ((float) width), 0.375f * ((float) height)), new PointF(0.375f * ((float) width), 0.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5416667f * ((float) width), 1.0f * ((float) height)), new PointF(0.5416667f * ((float) width), 0.45833334f * ((float) height)), new PointF(0.0f * ((float) width), 0.45833334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5416667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.45833334f * ((float) height)), new PointF(0.5416667f * ((float) width), 0.45833334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.45833334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.45833334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.45833334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.45833334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5833333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5833333f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5833333f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 1.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.0f * ((float) width), 0.33333334f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height)), new PointF(0.5f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), AdaptiveVideoTrackSelection.DEFAULT_BANDWIDTH_FRACTION * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.33333334f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.6666667f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        collageLayout = new CollageLayout(shapeList);
        collageLayout.useLine = false;
        this.collageLayoutList.add(collageLayout);
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5833333f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.41666666f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(1.0f * ((float) width), 0.33333334f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5833333f * ((float) height)), new PointF(0.5f * ((float) width), 0.5f * ((float) height)), new PointF(0.5833333f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(0.0f * ((float) width), 0.16666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.16666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.25f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.41666666f * ((float) height)), new PointF(1.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(0.0f * ((float) width), 0.6666667f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.6666667f * ((float) height)), new PointF(1.0f * ((float) width), 0.8333333f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
        shapeList = new ArrayList();
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.0f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height)), new PointF(0.0f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.0f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 0.5f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 0.5f * ((float) height)), new PointF(1.0f * ((float) width), 1.0f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height))});
        shapeList.add(new PointF[]{new PointF(0.0f * ((float) width), 0.5f * ((float) height)), new PointF(0.6666667f * ((float) width), 0.5f * ((float) height)), new PointF(0.33333334f * ((float) width), 1.0f * ((float) height)), new PointF(0.0f * ((float) width), 1.0f * ((float) height))});
        this.collageLayoutList.add(new CollageLayout(shapeList));
    }
}
